1. Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [8]:
import numpy as np
def vandermonde_matrix(input,n,boolean):
    if boolean==True:
        output=np.array([x**(n-i-1) for x in input for i in range(n)]).reshape(n,n)
    else:
        output=np.array([x**i for x in input for i in range(n)]).reshape(n,n)
    return output
input_mat=[]
size=int(input("Enter size of list"))
for i in range(size):
    input_mat.append(int(input("Enter the elements")))
print("Input array is:",input_mat)
print("Number of columns in output matrix:",size)
print("Output when decreasing powers:")
print(vandermonde_matrix(input_mat,size,True))
print("Output when increasing powers:")
print(vandermonde_matrix(input_mat,size,False))

Enter size of list3
Enter the elements1
Enter the elements2
Enter the elements3
Input array is: [1, 2, 3]
Number of columns in output matrix: 3
Output when decreasing powers:
[[1 1 1]
 [4 2 1]
 [9 3 1]]
Output when increasing powers:
[[1 1 1]
 [1 2 4]
 [1 3 9]]


2. Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [17]:
input_list=[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
window=3
"""cum_sum=np.cumsum(input_list)
cum_sum[:-3]
cum_sum[3:]"""

array([ 17,  25,  35,  46, 111, 183, 264, 363, 463, 613], dtype=int32)

In [19]:
def moving_average(input_list,n):
    cum_sum=np.cumsum(input_list)
    cum_sum[n:]=cum_sum[n:]-cum_sum[:-n]
    output=(cum_sum[n-1:]/n).round(3)
    return output
print("Output:",moving_average(input_list,size))
    

Output: [  5.      4.667   5.667   6.667   9.667  28.667  49.333  72.667  84.
  93.333 116.333]
